# https://render.com/docs/blueprint-spec
services:
  - type: web
    name: beat-battle
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: COOKUP_JWT_SECRET
        generateValue: true
